console.log(problem2(4000000));

function problem2(n=1000){
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

I've modified the problem so it can consider terms of any n

function returns sum of even values
*/

  //initialize terms
  t1=1;
  t2=2;
  t3=0;
  sum=2;
  finished=false;

  while (!finished){
    t3=t1+t2;
    if (t3< n) {
      t1=t2;
      t2=t3;
      if (t3 % 2 == 0) { sum = sum +t3;} //add even term to sum
    } else {
      finished=true;
    }
  }

  return(sum);

}
